# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07effd920ae63d0e61a750f54aca4caab32f4d1c9c20ef44e0faa038573318aa7c10f5fd19f13b8579b056e71f74efa670dd55c40f0e66f112233bbc3ba81fe0

test:
  secret_key_base: 2064ee184a6314642b2d05c62ef9b85a04242843d990de62dc3651184ffc6fa50fe64c24d3eb88eafb21e17eca1f7d6998d8791757d8dc877efed0eba7527d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
